# Generated by Django 2.2.9 on 2020-05-16 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200516_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 18, 7, 12, 622303, tzinfo=utc)),
        ),
    ]
